language: smalltalk
services:
- docker

env:
- SQUEAK_VERSION=5.3

smalltalk: "Squeak64-${SQUEAK_VERSION}"

before_script:
- | # Ignore missing figures during PDF build
  test $TRAVIS_BRANCH = master || export DEBUG_FIGURES=true
- set -o pipefail
script:
- smalltalkci .smalltalk.ston
- make | ./build_scripts/travis_fold Compiling PDF ...
- mv SBE.pdf "SBE_${SQUEAK_VERSION}.pdf"
- | # Upload PDF file to Google Drive
  if [ "$TRAVIS_PULL_REQUEST" = false ]
  then
    ./build_scripts/gdrive.sh upload "SBE_${SQUEAK_VERSION}.pdf"
  fi

jobs:
  include:
    - stage: deploy
      if: branch = master AND type = push
      name: GitHub Release
      env: SQUEAK_VERSION=
      language: minimal
      install: skip
      script: ./build_scripts/gdrive.sh download
      deploy:
        provider: releases
        file_glob: true
        file: SBE_*.pdf
        api_key: $GH_OAUTH_TOKEN
        skip_cleanup: true
        on:
          all_branches: true

notifications:
  email:
    if: type = cron
